CREATE TABLE [Identity].[UserProfiles]
(
	ID INT NOT NULL,
	GUID UNIQUEIDENTIFIER NOT NULL,
	DateCreated DATETIME2 NOT NULL,
	UpdateDate DATETIME2  NOT NULL,
	CONSTRAINT PK_UserProfiles_ID PRIMARY KEY(ID)
)
GO