CREATE TABLE [Users].[UserProfiles]
(
	ID INT NOT NULL,
	GUID UNIQUEIDENTIFIER NOT NULL,
	DateCreated DATETIME2 NOT NULL,
	DateUpdated DATETIME2  NOT NULL,
	CONSTRAINT PK_UserProfiles_ID PRIMARY KEY(ID),
	CONSTRAINT UX_UserProfiles UNIQUE ([GUID])
)
GO
